provider: datadog
major-version: 4
makeTemplate: bridged
env:
  DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
runner:
  publish: pulumi-ubuntu-8core
  buildSdk: pulumi-ubuntu-8core
